name: Build Plugin Zip

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build zip
        run: |
          set -e
          PLUGIN_SLUG="laposta-campaigns"
          WORKDIR="dist/${PLUGIN_SLUG}"
          mkdir -p "$WORKDIR"
          rsync -av --exclude ".git" --exclude ".github" --exclude "dist" --exclude ".DS_Store" --exclude "node_modules" ./ "$WORKDIR"/
          cd dist
          zip -r "${PLUGIN_SLUG}.zip" "${PLUGIN_SLUG}"
          echo "artifact=dist/${PLUGIN_SLUG}.zip" >> $GITHUB_OUTPUT
        id: build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laposta-campaigns-zip
          path: dist/laposta-campaigns.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laposta-campaigns-zip
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/laposta-campaigns.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


